// <auto-generated />
using System;
using HolidayChecklist.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HolidayChecklist.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181119021740_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("HolidayChecklist.Models.Episode", b =>
                {
                    b.Property<int>("ParentShowID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("First_Air_Date");

                    b.Property<string>("Overview");

                    b.Property<int>("ParentSeasonNumber");

                    b.Property<int?>("SeasonParentShowID");

                    b.Property<string>("Title");

                    b.HasKey("ParentShowID");

                    b.HasIndex("SeasonParentShowID");

                    b.ToTable("Episode");
                });

            modelBuilder.Entity("HolidayChecklist.Models.Season", b =>
                {
                    b.Property<int>("ParentShowID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("First_Air_Date");

                    b.Property<int>("SeasonNumber");

                    b.Property<int?>("TVShowId");

                    b.HasKey("ParentShowID");

                    b.HasIndex("TVShowId");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("HolidayChecklist.Models.TVShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Backdrop_Path");

                    b.Property<DateTime>("First_Air_Date");

                    b.Property<string>("Overview");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("TVShow");
                });

            modelBuilder.Entity("HolidayChecklist.Models.Episode", b =>
                {
                    b.HasOne("HolidayChecklist.Models.Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonParentShowID");
                });

            modelBuilder.Entity("HolidayChecklist.Models.Season", b =>
                {
                    b.HasOne("HolidayChecklist.Models.TVShow")
                        .WithMany("Seasons")
                        .HasForeignKey("TVShowId");
                });
#pragma warning restore 612, 618
        }
    }
}
